version: '2'
services:
  postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=temptation_test
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
